#sudo: required
language: node_js
node_js:
  - node

install:
  - npm i -g serverless
  - npm install --no-optional
    
script:
  - cd infrastructure && serverless deploy
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: stephanie.manwaring.io
  skip_cleanup: true
  local_dir: public
  detect_encoding: true
  acl: public_read
  on:
    all_branches: true